version: '3.8'

services:
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - API_TOKEN=${API_TOKEN}
      - NEWS_DATA_DIR=/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s